### ISSUE TITLE
correspondance between code and equation

### ISSUE THREAD

**Issue by JunMa11** [Digital-Dermatology/t-loss#2]
Hi @alvarogonjim ,

Thanks for the amazing work and congrats on the best paper award.

It seems that the code format doesn't align with the equation. Could you please reformat the code to match the equation?

<img width="811" alt="image" src="https://github.com/Digital-Dermatology/t-loss/assets/19947331/b4ea8292-33c0-43a9-8f78-2ff8a9eaabca">

![image](https://github.com/Digital-Dermatology/t-loss/assets/19947331/acd8ef0f-4dcb-4f10-8857-0b0f7e4850f9)

BTW, I also added your great work to the loss odyssey repo: https://github.com/JunMa11/SegLoss

**Comment by JunMa11** [comment]
Could you please also explain this variable a little bit?

https://github.com/Digital-Dermatology/t-loss/blob/37f6b7891db4629d5b9bd2125b31ed58e161bd8c/tloss.py#L87

**Comment by JunMa11** [comment]
Thank you very much for the great explanation.

**Comment by SamuelJoutard** [comment]
Hi, 

thank you for the code and the great work.

Shouldn't the prediction squared error be scaled by 1/(e(lambda) + eps) instead? 

Also in the code lambdas are all 1 which means that the diagonal matrix has entries close to exp(1). Isn't this strange? Shouldn't lambda be set to 0 as a canonical behavior?
